title: "BabyCart Vatakara"
email: babycart.vatakara@gmail.com
timezone: 'Asia/Kolkata'
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/babycart-logo-white-40x45.png'
favicon: 'assets/images/favicon.ico'
author: Sal
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# <!-- Google tag (gtag.js) -->
# <script async src="https://www.googletagmanager.com/gtag/js?id=G-P490WDRS4S"></script>
# <script>
#   window.dataLayer = window.dataLayer || [];
#   function gtag(){dataLayer.push(arguments);}
#   gtag('js', new Date());

#   gtag('config', 'G-P490WDRS4S');
# </script>


# Authors
authors:
  sal:
    name: Sal
    display_name: Sal
    avatar: 'assets/images/sal.png'
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: https://twitter.com/wowthemesnet
    description: "Author of Affiliates, a template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
  john:
    name: John
    display_name: John
    avatar: 'assets/images/john.png'
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Affiliates theme demo, a Jekyll template compatible with Github pages."

# Social
social:
  instagram: https://www.instagram.com/babycartvatakara/
  facebook: https://www.facebook.com/BabyCartVatakara/
  twitter: https://twitter.com/BabyCartVta
  whatsapp: https://wa.me/917907679962

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives